"""Add desktop-only storage hooks to canonical UI; replacement counts are checked."""
from pathlib import Path
root=Path(__file__).resolve().parents[2]
base=root/'docs/redesign'
def edit(file, before, after):
    p=base/file
    text=p.read_text(encoding='utf-8')
    if after in text: return
    if text.count(before)!=1: raise RuntimeError(f'{file}: expected unique {before[:80]!r}, got {text.count(before)}')
    p.write_text(text.replace(before,after),encoding='utf-8')

edit('preview-books.js',"  const homeState = id =>", "  if (window.desktopStore) { const saved=window.desktopStore.get('books'); books.splice(0,books.length,...(saved?.books || [])); bookNotes.clear(); (saved?.homes || []).forEach(([id,state])=>bookNotes.set(id,state)); nextId=saved?.nextId || 1; nextNoteId=saved?.nextNoteId || 1; selectedBookId=saved?.selectedBookId || books[0]?.id || 'main'; window.desktopStore.register('books',()=>({books,homes:[...bookNotes],nextId,nextNoteId,selectedBookId})); }\n  const homeState = id =>")
edit('preview-books.js',"const primary = books.find((book) => book.id === 'main');", "const primary = books.find((book) => book.id === selectedBookId) || books[0] || {name:'还没有作品',id:'main'};")
edit('preview-books.js',"id:'book-' + nextId++", "id:window.desktopStore && !books.length ? 'main' : 'book-' + nextId++")
edit('preview-books.js',"primaryTitle: () => books.find((book) => book.id === 'main').name,", "primaryTitle: () => (books.find((book) => book.id === (window.desktopStore ? selectedBookId : 'main')) || books[0])?.name || '未选择作品',\n    listBooks:()=>books.map(book=>({...book})),\n    removeBook(id) { const index=books.findIndex(book=>book.id===id); if(index<0)return;books.splice(index,1);bookNotes.delete(id);selectedBookId=books[0]?.id || 'main';render();switchView('home'); },")
edit('preview-books.js',"const book = books.find((item) => item.id === 'main'); book.chapters", "const book = books.find((item) => item.id === (window.desktopStore ? selectedBookId : 'main')); if(!book)return; book.chapters")
edit('preview-books.js',"currentBookContext:() => ({id:selectedBookId,...books.find(book => book.id === selectedBookId)}),", "currentBookContext:() => ({id:selectedBookId,name:'未选择作品',...books.find(book => book.id === selectedBookId)}),")
edit('preview-books.js',"selectedBookId = id; renderHome();", "selectedBookId = id; window.dispatchEvent(new CustomEvent('desktop-book-changed',{detail:{id}})); renderHome();")

edit('preview-pages.js',"  syncTemplates(); renderPeople(); Object.keys(collections).forEach(renderCollection);", "  if(window.desktopStore){const saved=window.desktopStore.get('pages');bookCards.clear();bookOutlineGroups.clear();(saved?.bookCards || []).forEach(([id,value])=>bookCards.set(id,value));(saved?.bookOutlines || []).forEach(([id,value])=>bookOutlineGroups.set(id,value));people=bookCards.get(activeBook.id)?.people || [];collections.world.groups=bookCards.get(activeBook.id)?.world || Object.fromEntries(Object.keys(collections.world.groups).map(key=>[key,[]]));collections.outline.groups=bookOutlineGroups.get(activeBook.id) || {大纲:[],章节细纲:[],伏笔:[]};if(saved?.library)Object.assign(collections.library.groups,saved.library);collections.ideas.groups.灵感=saved?.ideas?.灵感 || [];if(saved?.templates)templateStore.restore(saved.templates,templateStore.revision);nextCardId=saved?.nextCardId || 1;window.desktopStore.register('pages',()=>{bookCards.set(activeBook.id,{people,world:collections.world.groups});bookOutlineGroups.set(activeBook.id,collections.outline.groups);return {bookCards:[...bookCards],bookOutlines:[...bookOutlineGroups],library:collections.library.groups,ideas:{灵感:collections.ideas.groups.灵感},templates:templateStore.snapshot(),nextCardId};});}\n  syncTemplates(); renderPeople(); Object.keys(collections).forEach(renderCollection);")
edit('preview-pages.js',"  return {\n    setBook,", "  return {\n    setBook,\n    activeBookId:()=>activeBook.id,\n    removeBook(id){const state=bookCards.get(id);if(state)templateStore.syncBook(bookInfo(id)||{id,name:id},[],{});bookCards.delete(id);bookOutlineGroups.delete(id);refreshTemplates();},")

edit('preview-features.js',"  let cardTab = 'plot'", "  const cardsByBook=new Map();let cardsBookId='main';\n  if(window.desktopStore){const saved=window.desktopStore.get('features');(saved?.cardsByBook || []).forEach(([id,value])=>cardsByBook.set(id,value));Object.assign(cards,cardsByBook.get(cardsBookId) || {plot:[],scene:[]});window.desktopStore.register('features',()=>{cardsByBook.set(cardsBookId,{plot:cards.plot,scene:cards.scene});return {cardsByBook:[...cardsByBook]};});window.addEventListener('desktop-book-changed',event=>{cardsByBook.set(cardsBookId,{plot:cards.plot,scene:cards.scene});cardsBookId=event.detail.id;Object.assign(cards,cardsByBook.get(cardsBookId) || {plot:[],scene:[]});selectedCard=null;cardPage=1;renderCards();});}\n  let cardTab = 'plot'")
edit('preview-chapter-references.js',"  const state=id=>", "  if(window.desktopStore){(window.desktopStore.get('references')?.states || []).forEach(([key,value])=>states.set(key,value));window.desktopStore.register('references',()=>({states:[...states]}));}\n  const stateKey=id=>window.desktopStore ? pages.activeBookId()+':'+id : id;\n  const state=id=>")
edit('preview-chapter-references.js',"{if(!states.has(id))states.set(id,{people:[],world:[],foreshadowing:[]});return states.get(id);}", "{const key=stateKey(id);if(!states.has(key))states.set(key,{people:[],world:[],foreshadowing:[]});return states.get(key);}")
edit('preview-chapter-references.js',"const storyFor=id=>({...pages.getStoryContext('main',Number(id)),foreshadowing:pages.getForeshadowing('main')});", "const storyFor=id=>({...pages.getStoryContext(window.desktopStore?pages.activeBookId():'main',Number(id)),foreshadowing:pages.getForeshadowing(window.desktopStore?pages.activeBookId():'main')});")
edit('preview-reading-store.js',"  let db, revision = 0, queue", "  if(window.desktop){const key='reading-archive',raw=window.desktop.getKV(key),state=raw?JSON.parse(raw):{books:[],materials:[]};if(!window.previewReadingValid(state))throw new Error('阅读数据库格式异常，未覆盖原数据。');window.previewReadingArchive=clone(state);return {ready:Promise.resolve(clone(state)),snapshot:()=>clone(state),save:async value=>{if(!window.previewReadingValid(value))throw new Error('阅读格式异常');window.desktop.setKV(key,JSON.stringify(value));Object.assign(state,clone(value));window.previewReadingArchive=clone(value);window.dispatchEvent(new Event('preview-reading-change'));return clone(value);}};}\n  let db, revision = 0, queue")
print('Desktop state hooks connected')
