'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=__dirname,source=path.join(root,'../docs/redesign'),protect=process.argv.includes('--protect'),out=protect?path.join(root,'protected'):root,dist=path.join(out,'dist');
fs.mkdirSync(dist,{recursive:true});
const replacements=[
 ['练习稿、统计及人工核对保存在本机浏览器；题目为本地演示，未接入真实AI。','练习稿、分析与人工核对保存在本机数据库；题目由已配置的 AI 生成。'],
 ['灵感示例内容 · 本页修改刷新后恢复，不连接真实作品。','灵感保存在本机数据库，可选入作品作为核心主线。'],
 ['彩虹玻璃 / 11 个页面','本地创作空间'],['示例作品','作品'],['示例稿','草稿'],['示例正文','正文'],['示例章节','章节'],['预览稿件','正文'],['示例结果','结果'],['AI 示例采用','AI 采用'],['刷新恢复。','重新打开仍保留。'],['本机浏览器','本机数据库'],
 ['以下结果是本地示例，用于检查原有操作流程；不会发送正文、读取旧密钥或调用模型。','根据本次条件调用已配置的 AI。候选结果核对后才会写入作品。'],
 ['正在准备本地示例结果…','正在生成…'],['AI 辅助 · 设计预览','AI 辅助'],
 ['未发送真实AI请求','按本次条件准备'],['真实语义提炼尚未接入','生成后请核对原文依据'],
 ['当前本地预览提取原句作核对草稿，',''],['语义审核和按意见自动修订尚未接入真实AI。','正文生成会进行独立核对与一次局部修订；仍需作者确认。'],
 ['事实、因果、情绪及个人文风语义尚未由真实AI审核；没有报错不代表内容已通过语义终验。','请核对语义审核结果和原文依据，函数检查通过仍不代表语义一定准确。'],
 ['独立模型审核','独立调用审核'],['检查与终验 · 本地预览','检查与终验'],
 ['刷新恢复；','修改已保存；'],
 ['本页预览刷新恢复。','更换会保留旧灵感关联资料。'],['刷新恢复示例。','修改自动保存。'],['刷新恢复示例','修改自动保存'],['刷新后恢复示例','修改会保留'],['刷新后恢复。','设置会保留。'],
 ['不保存真实密钥，不发送请求；刷新清除。','配置保存后才能连接服务。'],
 ['不会调用真实 AI','需要保存 AI 配置'],['没有调用真实 AI','已调用配置的 AI'],['没有发送AI请求','请核对后采用'],
 ['当前为统计观察，真实AI尚未调用。','已独立核对语义观察，仍请逐项人工审核。'],['当前未发送真实AI请求。','下次分析将读取适用纠正。'],
 ['题目为本地演示；统计来自你的正文，未调用真实AI。','AI 出题，作者自行写作。统计与语义分析相互补充，逐项人工核对。'],
 ['保存在本机浏览器，刷新后仍可打开。其他作品预览仍按原规则恢复示例。','保存在本机数据库，修改版本与人工审核历史一起保留。'],
 ['情绪、描写和潜台词等语义判断待真实AI接入。','语义观察另有原文证据与人工核对，统计支持不等于准确率。'],
 ['已采用本地演示题目','已采用 AI 题目'],['演示主题','练习题目'],['AI 出题 · 演示','AI 出题'],
 ['本篇观察与人工核对','本篇分析与人工核对'],['生成示例结果','开始生成'],['重新生成示例','重新生成'],['示例 API Key','API Key'],['保留本页演示配置','保存 AI 配置'],['生成示例','生成'],['采用已选示例','采用已选结果'],['选择要采用的示例','选择要采用的结果'],
 ['结果确认后才写入本页正文','结果确认后才写入正文'],['真实作品不受影响。','请核对后采用。'],['其他生成仍为本页预览。','所有修改保存到本机数据库。'],
 ['演示模式 · ',''],['本机保存结果。','保存结果。'],['本页示例。','已保存结果。'],['本页试写','当前作品'],['本页预览','本机保存'],['本页内容','当前内容'],['本页正文','正文'],['本页示例','已保存内容'],['本页笔记','阅读笔记'],['本页保留','本机保留'],['本页预览中保留','数据库中保留'],['刷新清除','仅本次使用'],
 ['创建示例作品','创建作品'],['修改示例条目名称','修改条目'],['新建示例条目','新建条目'],['设计预览','桌面版'],['完整预览','桌面版'],['示例 · ',''],[' · 示例',''],
 ['当前为本地提取演示，请核对后确认，未调用 AI 服务。','调用 AI 提取并独立核对变化，请作者确认。'],
 ['这里演示配置表单。请使用示例值，当前页面不会连接服务或保存配置。','配置支持 OpenAI 兼容接口。正文及参考资料仅在点击生成后发送到你配置的服务。'],
 ['此处仅演示弹窗外观，内容不会保存到真实作品。','填写后保存到本机数据库。'],['演示结果不保证目标字数，差异由作者判断。','目标字数与实际字数的差异请作者判断。']
];
const transform=text=>replacements.reduce((s,[from,to])=>s.split(from).join(to),text);
const js=(code,name)=>protect?require('javascript-obfuscator').obfuscate(code,{compact:true,identifierNamesGenerator:'hexadecimal',stringArray:true,stringArrayEncoding:['base64'],stringArrayThreshold:.8,renameGlobals:false,sourceMap:false,controlFlowFlattening:false,target:name.endsWith('.cjs')?'node':'browser',seed:20261004}).getObfuscatedCode():code;
let html=fs.readFileSync(path.join(source,'ios26-preview.html'),'utf8');
html=html.replace(/<a href="ios26-preview-v8.html">.*?<\/a>/,'');
html=html.replace(/<script>\s*([\s\S]*?)<\/script>/g,(_,body)=>{fs.writeFileSync(path.join(dist,'application.js'),js(transform(body),'application.js'));return '<script src="application.js"></script>';});
const names=new Set([...html.matchAll(/(?:src|href)="((?:preview-)[^"?]+)(?:[^" ]*)"/g)].map(m=>m[1]));
for(const name of names){const file=path.join(source,name);if(!fs.existsSync(file))throw new Error('Missing '+name);fs.writeFileSync(path.join(dist,name),name.endsWith('.js')?js(transform(fs.readFileSync(file,'utf8')),name):fs.readFileSync(file));}
for(const name of ['renderer-store.js','renderer-ui.js','style-validation-core.js','style-validation.js','chapter-links.js','window-chrome.js'])fs.writeFileSync(path.join(dist,name),js(transform(fs.readFileSync(path.join(root,name),'utf8')),name));
fs.copyFileSync(path.join(root,'window-chrome.css'),path.join(dist,'window-chrome.css'));
html=html.replace('</head>','<link rel="stylesheet" href="window-chrome.css"></head>').replace('</body>','<script src="window-chrome.js"></script></body>');
html=transform(html).replace('</head>','<script src="chapter-links.js"></script><script src="renderer-store.js"></script></head>').replace('</body>','<script src="renderer-ui.js"></script><script src="style-validation-core.js"></script><script src="style-validation.js"></script></body>');
html=html.replace(/<details class="ai-demo-controls">[\s\S]*?<\/details>/g,''); // This markup is also generated by JS, hidden below.
html=html.replace('</head>',`<style>.ai-demo-controls{display:none!important}.desktop-template-version{display:flex;gap:16px;align-items:center;margin:14px 0}.desktop-template-version select{min-width:180px}.desktop-template-version[hidden]{display:none}.chapter-list .actions{margin-top:16px;flex-wrap:wrap}.chapter-list .actions .btn{font-size:12px;padding:8px;min-width:0}#desktop-save-status{margin-top:12px;width:100%;height:auto;white-space:normal;font-size:11px;line-height:1.6}.ai-context pre{white-space:pre-wrap}</style></head>`);
fs.writeFileSync(path.join(dist,'index.html'),html);
if(protect){
 fs.writeFileSync(path.join(out,'package.json'),JSON.stringify({name:'writing-workbench-protected',version:'0.2.0',description:'本地小说写作与 AI 辅助创作',author:'soryuu914-svg',main:'main.cjs',private:true}));fs.writeFileSync(path.join(out,'runtime.json'),JSON.stringify({protected:true}));
 for(const name of ['main.cjs','preload.cjs','storage.cjs','integrity.cjs','security.cjs'])fs.writeFileSync(path.join(out,name),js(fs.readFileSync(path.join(root,name),'utf8'),name));
 const key=crypto.randomBytes(32),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([cipher.update(js(fs.readFileSync(path.join(root,'ai.cjs'),'utf8'),'ai.cjs'),'utf8'),cipher.final()]);fs.writeFileSync(path.join(out,'engine.enc'),Buffer.concat([iv,cipher.getAuthTag(),encrypted]));
 const loader=`const fs=require('node:fs'),crypto=require('node:crypto'),Module=require('node:module'),path=require('node:path');const payload=fs.readFileSync(path.join(__dirname,'engine.enc')),dec=crypto.createDecipheriv('aes-256-gcm',Buffer.from('${key.toString('base64')}','base64'),payload.subarray(0,12));dec.setAuthTag(payload.subarray(12,28));const source=Buffer.concat([dec.update(payload.subarray(28)),dec.final()]).toString('utf8');const engine=new Module(__filename,module);engine.filename=__filename;engine.paths=module.paths;engine._compile(source,__filename);module.exports=engine.exports;`;
 fs.writeFileSync(path.join(out,'ai.cjs'),js(loader,'ai.cjs'));
 const manifest={version:1,files:{}};function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,entry.name);if(entry.isDirectory())walk(full);else if(entry.name!=='integrity.json')manifest.files[path.relative(out,full).replaceAll('\\','/')]=crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex');}}walk(out);fs.writeFileSync(path.join(out,'integrity.json'),JSON.stringify(manifest));
}
console.log(JSON.stringify({built:true,protected:protect,path:out,rendererFiles:names.size+4}));
