/* Desktop-only interactions; all business data is written through the preload bridge. */
(() => {
  if(!window.desktop)return;
  const $=id=>document.getElementById(id),node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
  const notice=text=>window.workbench?.notice(text);
  const button=(text,action,parent)=>{const b=node('button',text,'btn');b.type='button';b.addEventListener('click',async()=>{b.disabled=true;try{await action();}catch(error){notice(error.message);}finally{b.disabled=false;}});parent.append(b);return b;};
  const dialog=node('dialog');dialog.className='feature-dialog';dialog.innerHTML='<form id="desktop-material-form"><h2 id="desktop-material-heading"></h2><label for="desktop-material-title">名称 *</label><input id="desktop-material-title" maxlength="240" required><label for="desktop-material-body">内容 *</label><textarea id="desktop-material-body" maxlength="30000" rows="8" required></textarea><div id="desktop-material-extra"></div><p id="desktop-material-error" class="field-error" role="alert"></p><div class="actions"><button class="btn" type="button" id="desktop-material-cancel">取消</button><button class="btn primary" type="submit">保存</button></div></form>';document.body.append(dialog);
  let edit;
  window.desktopEditMaterial=(view,group,item,trigger)=>{edit={view,group,item,trigger};$('desktop-material-heading').textContent=(item?'修改':'新建')+group;$('desktop-material-title').value=item?.title || '';$('desktop-material-body').value=item?.summary || '';$('desktop-material-error').textContent='';const extra=$('desktop-material-extra');extra.replaceChildren();if(['写作技巧','避雷规则'].includes(group)){for(const label of ['适用范围','执行方法','例外','来源']){const caption=node('label',label),input=node('textarea');input.rows=2;input.maxLength=5000;input.dataset.label=label;input.value=item?.fields?.find(([key])=>key===label)?.[1] || '';caption.append(input);extra.append(caption);}}dialog.showModal();$('desktop-material-title').focus();};
  $('desktop-material-cancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>edit?.trigger?.focus());
  $('desktop-material-form').addEventListener('submit',event=>{event.preventDefault();if(event.isComposing)return;const title=$('desktop-material-title').value.trim(),summary=$('desktop-material-body').value.trim();if(!title || !summary)return;const fields=(edit.item?.fields || []).filter(([key])=>!['适用范围','执行方法','例外','来源'].includes(key));$('desktop-material-extra').querySelectorAll('textarea').forEach(input=>{if(input.value.trim())fields.push([input.dataset.label,input.value.trim()]);});const item={...edit.item,id:edit.item?.id || 'manual-'+crypto.randomUUID(),title,summary,kind:edit.item?.kind || (edit.group==='伏笔'?'未埋设':edit.group),fields};window.workbench.pages.saveMaterial(edit.view,edit.group,item);window.desktopStore.changed();dialog.close();});
  async function safeFlush(){while($('desktop-save-status')?.textContent==='正在保存…')await new Promise(r=>setTimeout(r,60));window.desktopStore.flush();}
  document.addEventListener('keydown',event=>{if((event.ctrlKey || event.metaKey)&&event.key.toLowerCase()==='s'&&!event.isComposing){event.preventDefault();safeFlush().then(()=>notice('已保存到本机数据库。')).catch(error=>notice(error.message));}});
  async function dataAction(name,reload=false){await safeFlush();const result=await window.desktop[name]();if(result?.canceled)return;if(reload)location.reload();else notice(result.path ? '已保存：'+result.path : '操作完成');}
  function chapterPosition(){const app=window.workbench;if(!app)return;const id=document.querySelector('[data-chapter][aria-pressed=true]')?.dataset.chapter,chapter=app.getWritingChapters().find(c=>String(c.id)===String(id));const outlines=app.pages.getAIContext('outline','章节细纲',app.books.currentBookContext().id).items;const outline=chapter&&window.desktopChapterLinks.resolve(chapter,outlines);const volume=outline?.fields?.find(([key])=>key==='所属卷')?.[1];$('chapter-eyebrow').textContent=(volume?volume+' / ':'')+'第'+(id || '1')+'章';document.querySelector('.document-identity p').textContent=volume?volume+' · 写作工作区':'写作工作区';document.querySelector('#directory-pane > p').textContent=app.books.primaryTitle();document.querySelector('#directory-pane .volume').textContent='全部章节';}
  window.addEventListener('preview-chapter-changed',chapterPosition);
  document.addEventListener('DOMContentLoaded',async()=>{
    const app=window.workbench;if(!app){$('notice').textContent='界面未能完整启动，请保留数据库并检查错误记录。';return;}
    if(app.books.listBooks().length){const book=app.books.currentBookContext();window.dispatchEvent(new CustomEvent('desktop-book-changed',{detail:{id:book.id}}));app.pages.setBook();}
    chapterPosition();
    const workspaceHint=document.querySelector('.workspace small');if(workspaceHint)workspaceHint.textContent='本机数据库 · 自动保存';
    document.querySelector('.home-bottom span:last-child').textContent='作品保存在本机';
    const textSettings=window.desktopStore.get('settings') || {};
    $('reduce-glass').checked=!!textSettings.reduceGlass;$('reduce-glass').dispatchEvent(new Event('change'));$('settings-glass').checked=!!textSettings.reduceGlass;
    $('preview-density').value=textSettings.density || 'compact';$('preview-density').dispatchEvent(new Event('change'));
    window.desktopStore.register('settings',()=>({reduceGlass:$('reduce-glass').checked,density:$('preview-density').value}));
    const workspace=$('settings-workspace');workspace.replaceChildren(node('h2','本机数据库'),node('p','作品、正文、设定、阅读稿、练习与审核记录统一保存在这里。'),node('p',window.desktopStore.info.databasePath,'settings-hint'));
    button('从旧版工作区迁移',()=>dataAction('importWorkspace',true),workspace);
    const backups=$('settings-backup');backups.replaceChildren(node('h2','备份与恢复'),node('p','完整数据库备份包含所有本机资料。恢复前会自动备份当前数据。JSON 导出不包含模型密钥。'));
    button('创建数据库备份',()=>dataAction('backup'),backups);button('恢复数据库备份',()=>dataAction('restore',true),backups);button('导出完整数据',()=>dataAction('exportData'),backups);button('导入完整数据',()=>dataAction('importData',true),backups);
    const transfer=$('transfer-view').querySelector('.page-heading');const actions=node('div',undefined,'actions');button('导出全部软件数据',()=>dataAction('exportData'),actions);button('导入备份数据',()=>dataAction('importData',true),actions);transfer.append(actions);
    const form=$('preview-ai-form');const key=$('preview-secret');key.placeholder='留空保留已保存密钥';
    const keyLabel=document.querySelector('[for="preview-secret"]');if(keyLabel)keyLabel.textContent='API Key';
    const sessionLabel=node('label',undefined,'setting');const sessionCheck=node('input');sessionCheck.type='checkbox';sessionCheck.id='desktop-ai-session';sessionLabel.append(sessionCheck,document.createTextNode('仅本次使用密钥'));form.append(sessionLabel);
    const reviewLabel=node('label','审核模型（可选，留空使用同一模型独立核对）');reviewLabel.htmlFor='desktop-review-model';const reviewInput=node('input');reviewInput.id='desktop-review-model';reviewInput.maxLength=240;form.append(reviewLabel,reviewInput);
    const aiStatus=node('p');aiStatus.id='desktop-ai-status';aiStatus.setAttribute('role','status');form.append(aiStatus);
    const history=node('section');history.append(node('h3','近期 AI 生成记录'));const historyList=node('div');history.append(historyList);button('查看生成记录',async()=>{const records=await window.desktop.history();historyList.replaceChildren();for(const record of records.filter(r=>r.value.stage==='result')){const row=node('details');row.append(node('summary',record.createdAt+' · '+(window.previewAIOperations[record.value.operation]?.label || '文风核对')));for(const candidate of record.value.candidates || [])row.append(node('h4',candidate.title),node('p',candidate.summary));historyList.append(row);}if(!historyList.children.length)historyList.append(node('p','暂无生成记录。'));},history);$('settings-ai').append(history);
    let config={};try{config=await window.desktop.getAIConfig();$('preview-endpoint').value=config.endpoint || '';$('preview-model').value=config.model || '';$('preview-max-tokens').value=config.maxTokens || 8192;reviewInput.value=config.reviewModel || '';sessionCheck.checked=!!config.sessionOnly;aiStatus.textContent=config.configured?'已保存配置；密钥由系统保护，不在页面回显。':'先填写配置，保存后才能使用 AI。';}catch(error){aiStatus.textContent=error.message;}
    form.querySelector('[type=submit]').textContent='保存 AI 配置';
    form.addEventListener('preview-ai-config-save',async()=>{const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const tokens=Number($('preview-max-tokens').value);if(!Number.isInteger(tokens)||tokens<1||tokens>131072)throw new Error('输出上限需要是 1–131072 的整数。');const value={endpoint:$('preview-endpoint').value.trim(),model:$('preview-model').value.trim(),reviewModel:reviewInput.value.trim(),maxTokens:tokens,sessionOnly:sessionCheck.checked};if(key.value.trim())value.apiKey=key.value.trim();config=await window.desktop.setAIConfig(value);key.value='';aiStatus.textContent=config.sessionOnly?'配置已保存，仅本次运行有效。':'配置已保存，密钥已加密。';$('preview-ai-config-error').textContent='';}catch(error){$('preview-ai-config-error').textContent=error.message;}finally{submit.disabled=false;}});
    const versionControl=node('label','查看书内同步资料的版本');versionControl.className='desktop-template-version';const version=node('select');version.id='desktop-template-version';for(const [value,label] of [['latest','书内最新版本'],['initial','初始模板']]){const option=node('option',label);option.value=value;version.append(option);}versionControl.append(version);$('library-list').before(versionControl);const refreshVersion=()=>{const group=document.querySelector('[data-collection-tab=library][aria-pressed=true]')?.dataset.group;versionControl.hidden=!['人物模板','世界模板'].includes(group);};version.onchange=()=>app.pages.setTemplateVersion(version.value);document.querySelectorAll('[data-collection-tab=library]').forEach(b=>b.addEventListener('click',refreshVersion));refreshVersion();
    const directory=$('directory-pane');const chapterActions=node('div',undefined,'actions');button('新建章节',()=>app.addChapter(),chapterActions);button('删除本章',()=>confirmAction('删除这一章？正文将从当前作品移除。',()=>app.removeChapter()),chapterActions);directory.append(chapterActions);
    const homeActions=$('bookhome-view').querySelector('.page-heading .actions');button('删除作品',()=>confirmAction('删除当前作品及书内正文与设定？公共资料库中的两份模板会保留。',()=>{const id=app.books.currentBookContext().id;app.pages.removeBook(id);app.deleteBookWriting(id);app.features.removeBook?.(id);app.books.removeBook(id);window.desktopStore.changed();}),homeActions);
    ['outline','library'].forEach(view=>{const owner=$(view+'-detail');if(!owner)return;button('删除条目',()=>{const group=document.querySelector('[data-collection-tab='+view+'][aria-pressed=true]').dataset.group;if(['人物模板','世界模板','阅读与拆书'].includes(group))throw new Error('同步模板保留历史，来源卡片请在书内修改。');const ctx=app.pages.getAIContext(view,group);const item=ctx.items.find(c=>c.id===ctx.selected);if(!item)throw new Error('请先选择一个条目。');return confirmAction('删除「'+item.title+'」？',()=>{app.pages.removeMaterial(view,group,item.id);window.desktopStore.changed();});},owner);});
    // Avoid duplicate UI for practices: the saved/versioned practice workflow owns these actions.
    ['prompt','practice','style'].forEach(op=>document.querySelectorAll('#practice-panel [data-ai-operation='+op+']').forEach(b=>b.hidden=true));
    $('notice').textContent='本机数据库已打开。AI 结果先核对、后采用；所有修改自动保存。';
  });
  function confirmAction(message,action){return new Promise((resolve,reject)=>{const d=node('dialog');d.className='feature-dialog';d.append(node('h2','确认操作'),node('p',message));const controls=node('div',undefined,'actions');d.append(controls);let done=false;button('取消',()=>{done=true;d.close();resolve();},controls);button('确认',async()=>{try{await action();done=true;d.close();resolve();}catch(e){reject(e);d.close();}},controls);d.addEventListener('close',()=>{d.remove();if(!done)resolve();});document.body.append(d);d.showModal();});}
  window.desktopAllSearchDocuments=()=>{const app=window.workbench;if(!app)return[];const data=window.desktopStore.capture(),active=app.pages.activeBookId(),docs=[];const push=(bookId,view,group,item,type=view)=>{docs.push({id:bookId+':'+view+':'+item.id,bookId,view,type,group,target:item.id,title:item.title,path:(app.books.bookInfo(bookId)?.name || bookId)+' / '+group,fields:[{label:'名称',key:'title',text:item.title},{label:'内容',key:'summary',text:item.summary || ''},...(item.fields || []).map(([label,text],i)=>({label,text,key:i}))]});};for(const [id,state] of data.writing?.books || []){if(id===data.writing.activeBookId)continue;for(const [chapterId,c] of Object.entries(state.chapters))docs.push({id:id+':chapter:'+chapterId,bookId:id,type:'chapters',view:'editor',title:c.title,path:(app.books.bookInfo(id)?.name || id)+' / 正文',target:chapterId,fields:[{label:'章节名',key:'title',text:c.title},{label:'正文',key:'body',text:c.paragraphs.join('\n\n')},{label:'摘要',key:'summary',text:c.summary || ''}]});}for(const [id,groups] of data.pages?.bookOutlines || []){if(id===active)continue;Object.entries(groups).forEach(([group,items])=>items.forEach(item=>push(id,'outline',group,item)));}for(const [id,groups] of data.features?.cardsByBook || []){if(id===active)continue;Object.entries(groups).forEach(([group,items])=>items.forEach(item=>push(id,'cards',group,{...item,summary:item.description,fields:[['标签',(item.tags || []).join('、')]]},group==='plot'?'plots':'scenes')));}return docs;};
})();
