const http=require('node:http');
async function createSmokeAPI(){const calls=[];const server=http.createServer(async(req,res)=>{let text='';for await(const chunk of req)text+=chunk;const body=JSON.parse(text),system=body.messages[0].content,data=JSON.parse(body.messages[1].content);calls.push({system,data});let result;
 if(system.includes('你是独立审核者')){result={status:'pass',issues:[]};if(data.operation==='practice')result.claimReviews=data.candidates[0].claims.map(c=>({id:c.id,status:'supported',reason:'本机测试原文支持'}));}
 else {const values=data.values || {},context=data.context || {},operation=data.operation;const count=['passage','bookAnalysis'].includes(operation)?values.dimensions.length:operation==='outline'?Number(values.volumes || 1):operation==='volumeChapters'?context.structureNodes.length:['ideas','golden','person'].includes(operation)?3:1;
 result=Array.from({length:count},(_,i)=>({title:operation==='outline'?'第一卷 · 守城':operation==='volumeChapters'?'山门的选择':operation==='ideas'?'主线灵感 '+(i+1):operation==='golden'?'寻路能力 '+(i+1):'生成候选',summary:operation==='full'?'张三站在青云宗前，循着寻路能力找到被困的家人。':operation==='ideas'?'少年获得寻路能力，为救家人进入青云宗。':operation==='golden'?'基于已选灵感的寻路能力，只指向相关线索。':operation==='outline'?'循线进入青云宗，找到家人的下落。':operation==='volumeChapters'?'张三进入青云宗寻找被困家人，面对守门人的盘问作出选择。':operation==='practice'?'本篇以具体动作承载情绪。':operation==='summary'?'张三在青云宗找到家人。':'本机测试结果',fields:operation==='outline'?[['章节计划',context.structureNodes.map(n=>n+'：寻找家人').join('\n')]]:['summary','passage'].includes(operation)?[['原文依据',values.source]]:operation==='bookAnalysis'?[['原文依据',context.reading.chapters[0].body]]:[]}));
 if(['techniques','mergeRules'].includes(operation)){const pair=context.mergeItems.filter(x=>x.title.startsWith('合并走查'));result=pair.length>=2?[{title:'合并走查：限制破折号',summary:'不要使用破折号；保留原规则的较严格要求。',fields:[['适用场景','正文生成']],sourceIds:pair.slice(0,2).map(x=>x.id)}]:[];}
 if(operation==='practice')result[0].claims=[{id:'sensory-action',label:'以动作承载情绪',dimension:'情绪表达',definition:'仅作本篇观察',evidence:[values.source.slice(0,20)]}];}
 res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(result)}}]}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));return {url:'http://127.0.0.1:'+server.address().port+'/v1',calls,close(){server.closeAllConnections();server.close();}};}
module.exports={createSmokeAPI};
